export type CatalogItem = {
  id: string;
  name: string;
  neighborhood: string;
  category: "dinner" | "drinks" | "live_music" | "comedy" | "activity";
  start: string;
  durationMinutes: number;
  costPerPerson: number;
  bookingStatus: "not_needed" | "recommended" | "required" | "ticket_required" | "limited_availability";
  description: string;
  sourceUrl: string;
  availabilityUpdatedAt: string;
  availabilityNote?: string;
  latitude: number;
  longitude: number;
  arrivalTime?: string;
  doorsTime?: string;
  endTime?: string;
  imageUrl?: string;
  travelToNext?: { distanceMiles: number; minutes: number; mode: string };
  tags?: string[];
};

// Starter data for the Boston prototype. Replace with licensed provider data before launch.
export const bostonCatalog: CatalogItem[] = [
  { id: "row-34-seaport", name: "Row 34", neighborhood: "Seaport", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 55, bookingStatus: "recommended", description: "Oyster bar and seafood dinner", sourceUrl: "https://www.row34.com/locations-and-reservations/", availabilityUpdatedAt: "unknown", latitude: 42.3512, longitude: -71.0479 },
  { id: "baleia", name: "Baleia", neighborhood: "South End", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 48, bookingStatus: "recommended", description: "Portuguese-inspired seafood and wine", sourceUrl: "https://resy.com/cities/boston-ma/venues/baleia", availabilityUpdatedAt: "unknown", latitude: 42.3444, longitude: -71.0662 },
  { id: "srv", name: "SRV", neighborhood: "South End", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 55, bookingStatus: "recommended", description: "Venetian small plates, pasta, and cocktails", sourceUrl: "https://resy.com/cities/boston-ma/list/events", availabilityUpdatedAt: "unknown", latitude: 42.3437, longitude: -71.0695 },
  { id: "pier-6", name: "Pier 6 Boston Waterfront", neighborhood: "Charlestown", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 50, bookingStatus: "recommended", description: "Waterfront seafood dinner", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_1003", availabilityUpdatedAt: "unknown", latitude: 42.3757, longitude: -71.0526 },
  { id: "matria", name: "Matria", neighborhood: "Downtown", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 58, bookingStatus: "recommended", description: "Italian steakhouse and cocktail bar", sourceUrl: "https://resy.com/cities/boston-ma/list/events", availabilityUpdatedAt: "unknown", latitude: 42.3560, longitude: -71.0546 },
  { id: "reelhouse", name: "ReelHouse East Boston Waterfront", neighborhood: "East Boston", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 52, bookingStatus: "recommended", description: "Harborfront seafood and cocktails", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_1003", availabilityUpdatedAt: "unknown", latitude: 42.3618, longitude: -71.0280 },
  { id: "woods-hill", name: "Woods Hill Pier 4", neighborhood: "Seaport", category: "dinner", start: "18:30", durationMinutes: 90, costPerPerson: 60, bookingStatus: "recommended", description: "Farm-focused waterfront dining", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_1003", availabilityUpdatedAt: "unknown", latitude: 42.3527, longitude: -71.0442 },
  { id: "wallys-cafe", name: "Wally's Café Jazz Club", neighborhood: "South End", category: "live_music", start: "20:15", durationMinutes: 90, costPerPerson: 15, bookingStatus: "not_needed", description: "Live jazz; verify the nightly schedule", sourceUrl: "https://wallyscafe.com/visit-wallys/", availabilityUpdatedAt: "unknown", latitude: 42.3425, longitude: -71.0833 },
  { id: "wink-and-nod", name: "Wink & Nod", neighborhood: "South End", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 30, bookingStatus: "recommended", description: "Intimate cocktail lounge", sourceUrl: "https://www.winkandnod.com/", availabilityUpdatedAt: "unknown", latitude: 42.3442, longitude: -71.0759, tags: ["Cocktails", "Lounges", "Speakeasies"] },
  { id: "alibi", name: "Alibi Bar and Lounge", neighborhood: "Beacon Hill", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 26, bookingStatus: "recommended", description: "Historic hotel lounge with creative cocktails", sourceUrl: "https://resy.com/cities/boston-ma/venues/alibi-bar-and-lounge", availabilityUpdatedAt: "unknown", latitude: 42.3617, longitude: -71.0706, tags: ["Cocktails", "Lounges"] },
  { id: "parla", name: "Parla", neighborhood: "North End", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 25, bookingStatus: "recommended", description: "Whimsical cocktails and Italian bites", sourceUrl: "https://resy.com/cities/boston-ma/venues/parla", availabilityUpdatedAt: "unknown", latitude: 42.3640, longitude: -71.0548, tags: ["Cocktails", "Speakeasies", "Lounges"] },
  { id: "folio", name: "Folio", neighborhood: "Beacon Hill", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 24, bookingStatus: "recommended", description: "Wine-forward bistro and cocktail bar", sourceUrl: "https://resy.com/cities/boston-ma/venues/folio", availabilityUpdatedAt: "unknown", latitude: 42.3575, longitude: -71.0623, tags: ["Wine bars", "Cocktails", "Lounges"] },
  { id: "haley-henry", name: "haley.henry Wine Bar", neighborhood: "Downtown Crossing", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 22, bookingStatus: "not_needed", description: "Natural wine and small plates", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_956", availabilityUpdatedAt: "unknown", latitude: 42.3577, longitude: -71.0606, tags: ["Wine bars"] },
  { id: "nathalie", name: "nathálie Wine Bar", neighborhood: "Fenway", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 24, bookingStatus: "recommended", description: "Natural wines and late-night bites", sourceUrl: "https://resy.com/cities/boston-ma/list/events", availabilityUpdatedAt: "unknown", latitude: 42.3450, longitude: -71.0960, tags: ["Wine bars"] },
  { id: "zuzus-petals", name: "Zuzu's Petals", neighborhood: "Cambridge", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 22, bookingStatus: "recommended", description: "Cozy wine bar with a lounge feel", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_1003", availabilityUpdatedAt: "unknown", latitude: 42.3738, longitude: -71.1160, tags: ["Wine bars", "Lounges"] },
  { id: "street-bar", name: "The Street Bar", neighborhood: "Back Bay", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 28, bookingStatus: "recommended", description: "Classic hotel cocktails and bar bites", sourceUrl: "https://resy.com/cities/boston-ma/list/events", availabilityUpdatedAt: "unknown", latitude: 42.3495, longitude: -71.0798, tags: ["Cocktails", "Lounges"] },
  { id: "bogies-place", name: "Bogie's Place", neighborhood: "Downtown Crossing", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 34, bookingStatus: "required", description: "Hidden steakhouse with a speakeasy feel", sourceUrl: "https://resy.com/cities/boston-ma/list/bostons-essential-cozy-locales", availabilityUpdatedAt: "unknown", latitude: 42.3548, longitude: -71.0617, tags: ["Speakeasies", "Cocktails"] },
  { id: "parla-xxi", name: "Parla XXI", neighborhood: "Assembly Row", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 26, bookingStatus: "recommended", description: "Speakeasy-style cocktails and Italian plates", sourceUrl: "https://resy.com/cities/boston-ma/venues/parla-somerville", availabilityUpdatedAt: "unknown", latitude: 42.3943, longitude: -71.0786, tags: ["Cocktails", "Speakeasies", "Lounges"] },
  { id: "stratus", name: "Stratus Rooftop Bar", neighborhood: "Back Bay", category: "drinks", start: "21:45", durationMinutes: 75, costPerPerson: 28, bookingStatus: "recommended", description: "Skyline-view rooftop cocktails", sourceUrl: "https://viewboston.com/stratus/", availabilityUpdatedAt: "unknown", latitude: 42.3471, longitude: -71.0825, tags: ["Rooftop bars", "Cocktails"] },
  { id: "scores", name: "Scores", neighborhood: "West End", category: "drinks", start: "21:30", durationMinutes: 75, costPerPerson: 18, bookingStatus: "not_needed", description: "Two-level sports bar with food and drinks", sourceUrl: "https://resy.com/cities/boston-ma/list/collection_956", availabilityUpdatedAt: "unknown", latitude: 42.3653, longitude: -71.0623, tags: ["Sports bars"] },
  { id: "lookout-rooftop", name: "Lookout Rooftop", neighborhood: "Seaport", category: "drinks", start: "21:40", durationMinutes: 75, costPerPerson: 32, bookingStatus: "recommended", description: "Rooftop cocktails with harbor views", sourceUrl: "https://www.lookoutrooftop.com/", availabilityUpdatedAt: "unknown", latitude: 42.3537, longitude: -71.0435, tags: ["Cocktails", "Rooftop bars", "Lounges"] },
  { id: "trillium-fort-point", name: "Trillium Fort Point", neighborhood: "Fort Point", category: "drinks", start: "21:30", durationMinutes: 70, costPerPerson: 20, bookingStatus: "not_needed", description: "Boston brewery and beer garden", sourceUrl: "https://trilliumbrewing.com/", availabilityUpdatedAt: "unknown", latitude: 42.3517, longitude: -71.0471, tags: ["Breweries"] },
  { id: "city-winery", name: "City Winery Boston", neighborhood: "West End", category: "drinks", start: "21:30", durationMinutes: 75, costPerPerson: 24, bookingStatus: "recommended", description: "Wine bar with live entertainment", sourceUrl: "https://resy.com/cities/boston-ma/list/events", availabilityUpdatedAt: "unknown", latitude: 42.3653, longitude: -71.0628, tags: ["Wine bars", "Cocktails"] },
  { id: "yvonne-s", name: "Yvonne's", neighborhood: "Downtown Crossing", category: "dinner", start: "18:45", durationMinutes: 75, costPerPerson: 55, bookingStatus: "recommended", description: "Dinner and cocktails", sourceUrl: "https://www.yvonnesboston.com/", availabilityUpdatedAt: "unknown", latitude: 42.3554, longitude: -71.0607 },
  { id: "laugh-boston", name: "Laugh Boston", neighborhood: "Seaport", category: "comedy", start: "20:30", durationMinutes: 80, costPerPerson: 30, bookingStatus: "ticket_required", description: "Check the current show schedule", sourceUrl: "https://www.laughboston.com/", availabilityUpdatedAt: "unknown", latitude: 42.3509, longitude: -71.0460 },
  { id: "kings-seaport", name: "Kings Dining & Entertainment", neighborhood: "Seaport", category: "activity", start: "20:00", durationMinutes: 75, costPerPerson: 22, bookingStatus: "recommended", description: "Bowling, games, and food", sourceUrl: "https://www.kingsbowling.com/", availabilityUpdatedAt: "unknown", latitude: 42.3492, longitude: -71.0412 },
];
